/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cooptest.view.selectcoop;

import com.cooptest.dao.PersonTypeDao;
import com.cooptest.datatransfer.CooperatedDto;
import com.cooptest.datatransfer.PersonTypeDto;
import com.cooptest.model.Concept;
import com.cooptest.model.Cooperated;
import com.cooptest.model.Nationality;
import com.cooptest.model.PersonType;
import com.cooptest.references.Frames;
import com.cooptest.view.sale.Sale;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose_
 */
public class SelectCoop extends javax.swing.JFrame {
    private static PersonTypeDao personTypeDao;
    
    /**
     * Creates new form SelectCoop
     */
    public SelectCoop(PersonTypeDao personTypeDao) {
        initComponents();
        
        SelectCoop.personTypeDao = personTypeDao;
        
        setLocationRelativeTo(null);
        
        fillSearchResult();
    }

    private void fillSearchResult(){
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableResults.getModel();
            
        tableResults.setModel(defaultTableModel);

        defaultTableModel.setRowCount(0);
            
        for (Cooperated cooperated : CooperatedDto.getDatas()) {
            String name = cooperated.getNome();
            String email = cooperated.getEmail();
            String phone = cooperated.getTelefone();
            String nationality = cooperated.getNationality().getNome();
            String concept = cooperated.getConcept().getNome();
            String personType = cooperated.getPersonType().getNome();
            
            defaultTableModel.addRow(new Object[]{name, email, phone, nationality, concept, personType});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("* Dê dois cliques para selecionar o cooperado"));

        tableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "nome", "E-mail", "Telefone", "Nacionalidade", "Conceito", "Tipo de pessoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Frames.selectCoop = null;
    }//GEN-LAST:event_formWindowClosed

    private void tableResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableResultsMouseClicked
        if (evt.getClickCount() == 2){
            try{
                personTypeDao.connect();
                
                int row = tableResults.getSelectedRow();

                Cooperated cooperated = new Cooperated();

                cooperated.setNome(String.valueOf(tableResults.getValueAt(row, 0)));
                cooperated.setEmail(String.valueOf(tableResults.getValueAt(row, 1)));
                cooperated.setTelefone(String.valueOf(tableResults.getValueAt(row, 2)));
                cooperated.setNationality(new Nationality(String.valueOf(tableResults.getValueAt(row, 3))));
                cooperated.setConcept(new Concept(String.valueOf(tableResults.getValueAt(row, 4))));

                String personTypeName = String.valueOf(tableResults.getValueAt(row, 5));
                ResultSet resultSet = personTypeDao.findByName(personTypeName);
                resultSet.next();
                PersonType personType = new PersonType(resultSet.getInt("id"), personTypeName);
                cooperated.setPersonType(personType);

                PersonTypeDto.setData(personType);

                CooperatedDto.setData(cooperated);

                ((Sale) Frames.sale).popFilteredData();

                dispose();
            }catch(SQLException e){
                System.err.println(e.getMessage());
            } finally {
                personTypeDao.closeConnection(personTypeDao.getConnection());
            }
        }
    }//GEN-LAST:event_tableResultsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SelectCoop(personTypeDao).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResults;
    // End of variables declaration//GEN-END:variables
}
